default:

geco_2023:
  geco_2023_raw_path: "geco_2023-20240201"
  geco_2023_15c_raw_filename: "20240129_PACTA data request_GECO data template_15C_data.xlsx"
  geco_2023_ndc_raw_filename: "20240129_PACTA data request_GECO data template_NDC-LTS_data.xlsx"
  geco_2023_ref_raw_filename: "20240129_PACTA data request_GECO data template_Ref_data.xlsx"
  geco_2023_supplement_path: "geco_2023_supplemental-20240227/GECO2023_20231219"
  geco_2023_supplement_15c_raw_filename: "GECO2023_20231219_15C_Total.xlsx"
  geco_2023_supplement_ndc_raw_filename: "GECO2023_20231219_NDC_Total.xlsx"
  geco_2023_supplement_ref_raw_filename: "GECO2023_20231219_Ref_Total.xlsx"

2023Q4:
  inherits: geco_2023
