default:
  default: "default" # default config must have at least one key-value

geco_2022:
  geco_2022_path: "00Imported/GECO2022"
  geco_2022_automotive_filename: "geco2022_automotive_stocks_geco2021_retirement_rates_CORRECTED.csv"
  geco_2022_aviation_filename: "GECO2022_Aviation_processed_data.csv"
  geco_2022_fossil_fuels_15c_filename: "geco2022_15c_ff_rawdata.csv"
  geco_2022_fossil_fuels_ndc_filename: "geco2022_ndc_ff_rawdata.csv"
  geco_2022_fossil_fuels_ref_filename: "geco2022_ref_ff_rawdata.csv"
  geco_2022_power_15c_filename: "geco2022_15c_power_rawdata_region.csv"
  geco_2022_power_ndc_filename: "geco2022_ndc_power_rawdata_region.csv"
  geco_2022_power_ref_filename: "geco2022_ref_power_rawdata_region.csv"
  geco_2022_steel_filename: "GECO2022_Steel_processed_data.csv"

geco_2023:
  geco_2023_raw_path: "geco_2023-20240201"
  geco_2023_15c_raw_filename: "20240129_PACTA data request_GECO data template_15C_data.xlsx"
  geco_2023_ndc_raw_filename: "20240129_PACTA data request_GECO data template_NDC-LTS_data.xlsx"
  geco_2023_ref_raw_filename: "20240129_PACTA data request_GECO data template_Ref_data.xlsx"
  geco_2023_supplement_path: "geco_2023_supplemental-20240227/GECO2023_20231219"
  geco_2023_supplement_15c_raw_filename: "GECO2023_20231219_15C_Total.xlsx"
  geco_2023_supplement_ndc_raw_filename: "GECO2023_20231219_NDC_Total.xlsx"
  geco_2023_supplement_ref_raw_filename: "GECO2023_20231219_Ref_Total.xlsx"

isf_2021:
  isf_2021_raw_path: "00Imported/ISF2021"
  isf_2021_power_raw_filename: "NZAOA_raw_data_power.xlsx"
  isf_2021_not_power_raw_filename: "NZAOA_rawdata_notpower_P4I.xlsx"

isf_2023:
  isf_2023_raw_path: "isf_2023-20240222"
  isf_2023_scope_global_raw_filepath: "doi_10_5061_dryad_cz8w9gj82__v20230901/4.7 Database_August_upload/Scope_Country/Scope_Global.xlsx"
  isf_2023_s_global_raw_filepath: "doi_10_5061_dryad_cz8w9gj82__v20230901/4.7 Database_August_upload/S_Country/S_Global.xlsx"
  isf_2023_country_annex_path: "doi_10_5061_dryad_cz8w9gj82__v20230901/4.7 Database_August_upload/Annex_Country"

weo_2022:
  weo_2022_raw_path: "00Imported/WEO2022 extended data/WEO2022 extended data"
  weo_2022_ext_data_regions_raw_filepath: "raw_data_from_provider/used_in_pacta.scenario_preparation/WEO2022_Extended_Data_Regions.csv"
  weo_2022_ext_data_world_raw_filepath: "raw_data_from_provider/used_in_pacta.scenario_preparation/WEO2022_Extended_Data_World.csv"
  weo_2022_fossil_fuels_raw_filepath: "light_process/weo2022_fossilfuel_demand_supply.csv"
  weo_2022_nze_auto_raw_filepath: "processed_data/nze_may_2021_report_old_data/hard_process_auto/used/NZE2021_RawData_2050.xlsx"
  weo_2022_nze_steel_raw_filepath: "raw_data_from_provider/used_in_pacta.scenario_preparation/WEO2022_NZE_SteelData.csv"
  weo_2022_sales_aps_auto_raw_filepath: "raw_data_from_provider/used_in_pacta.scenario_preparation/SalesAPS_rawdata.csv"
  weo_2022_electric_sales_aps_auto_raw_filename: "raw_data_from_provider/used_in_pacta.scenario_preparation/IEA-EV-dataEV salesCarsProjection-APS.csv"

weo_2023:
  weo_2023_raw_path: "weo_2023-20240222/WEO2023 extended data"
  weo_2023_ext_data_regions_raw_filename: "WEO2023_Extended_Data_Regions.csv"
  weo_2023_ext_data_world_raw_filename: "WEO2023_Extended_Data_World.csv"
  weo_2023_fig_chptr_3_raw_filename: "WEO2023_Figures_Chapter_03.xlsx"
  iea_global_ev_raw_path: "iea_global_ev_2023-20240226"
  iea_global_ev_raw_filename: "IEA Global EV Data 2023.csv"
  mpp_ats_raw_path: "mpp_ats-20240227"
  mpp_ats_raw_filename: "2022-08-12 - MPP ATS - RPK and GHG intensity.xlsx"

weo_2024_ecb:
  weo_2024_raw_path: "weo_2024/WEO2024 extended data"
  weo_2024_ext_data_regions_raw_filename: "WEO2024_Extended_Data_Regions.csv"
  weo_2024_ext_data_world_raw_filename: "WEO2024_Extended_Data_World.csv"
  weo_2024_fig_chptr_3_raw_full_filename: 'WEO2024_Figures_Chapter_03.xlsx'
  iea_global_ev_raw_filename: "electric-vehicle-sales-by-region-and-scenario-2030-and-2035.xlsx"
  mpp_ats_raw_path: "mpp_ats-20240227"
  mpp_ats_raw_filename: "2022-08-12 - MPP ATS - RPK and GHG intensity.xlsx"

2022Q4:
  inherits: [geco_2022, isf_2021, weo_2022]

2023Q4:
  inherits: [geco_2023, isf_2023, weo_2023]

2024Q4:
  inherits: [weo_2024_ecb]
