default:
  default: "default" # default config must have at least one key-value

geco_2022:
  geco_2022_path: "geco_2022"
  geco_2022_automotive_filename: "geco2022_automotive_stocks_geco2021_retirement_rates_CORRECTED.csv"
  geco_2022_aviation_filename: "GECO2022_Aviation_processed_data.csv"
  geco_2022_fossil_fuels_15c_filename: "geco2022_15c_ff_rawdata.csv"
  geco_2022_fossil_fuels_ndc_filename: "geco2022_ndc_ff_rawdata.csv"
  geco_2022_fossil_fuels_ref_filename: "geco2022_ref_ff_rawdata.csv"
  geco_2022_power_15c_filename: "geco2022_15c_power_rawdata_region.csv"
  geco_2022_power_ndc_filename: "geco2022_ndc_power_rawdata_region.csv"
  geco_2022_power_ref_filename: "geco2022_ref_power_rawdata_region.csv"
  geco_2022_steel_filename: "GECO2022_Steel_processed_data.csv"

geco_2023:
  geco_2023_raw_path: "geco_2023-20240201"
  geco_2023_15c_raw_filename: "20240129_PACTA data request_GECO data template_15C_data.xlsx"
  geco_2023_ndc_raw_filename: "20240129_PACTA data request_GECO data template_NDC-LTS_data.xlsx"
  geco_2023_ref_raw_filename: "20240129_PACTA data request_GECO data template_Ref_data.xlsx"
  geco_2023_supplement_path: "geco_2023_supplemental-20240227/GECO2023_20231219"
  geco_2023_supplement_15c_raw_filename: "GECO2023_20231219_15C_Total.xlsx"
  geco_2023_supplement_ndc_raw_filename: "GECO2023_20231219_NDC_Total.xlsx"
  geco_2023_supplement_ref_raw_filename: "GECO2023_20231219_Ref_Total.xlsx"

isf_2021:
  isf_2021_raw_path: "ISF2021"
  isf_2021_power_raw_filename: "NZAOA_raw_data_power.xlsx"
  isf_2021_not_power_raw_filename: "NZAOA_rawdata_notpower_P4I.xlsx"

isf_2023:
  isf_2023_raw_path: "isf_2023-20240222"
  isf_2023_scope_global_raw_filepath: "doi_10_5061_dryad_cz8w9gj82__v20230901/4.7 Database_August_upload/Scope_Country/Scope_Global.xlsx"
  isf_2023_s_global_raw_filepath: "doi_10_5061_dryad_cz8w9gj82__v20230901/4.7 Database_August_upload/S_Country/S_Global.xlsx"
  isf_2023_country_annex_path: "doi_10_5061_dryad_cz8w9gj82__v20230901/4.7 Database_August_upload/Annex_Country"

weo_2023:
  weo_2023_raw_path: "weo_2023-20240222/WEO2023 extended data"
  weo_2023_ext_data_regions_raw_filename: "WEO2023_Extended_Data_Regions.csv"
  weo_2023_ext_data_world_raw_filename: "WEO2023_Extended_Data_World.csv"
  weo_2023_fig_chptr_3_raw_filename: "WEO2023_Figures_Chapter_03.xlsx"
  iea_global_ev_raw_path: "iea_global_ev_2023-20240226"
  iea_global_ev_raw_filename: "IEA Global EV Data 2023.csv"
  mpp_ats_raw_path: "mpp_ats-20240227"
  mpp_ats_raw_filename: "2022-08-12 - MPP ATS - RPK and GHG intensity.xlsx"

2022Q4:
  inherits: [geco_2022, isf_2021]

2023Q4:
  inherits: [geco_2023, isf_2023, weo_2023]
