services:
  scenario_prep:
    platform: linux/amd64
    build:
      context: .
    environment:
      R_CONFIG_ACTIVE: ${R_CONFIG_ACTIVE:-2022Q4}
      SCENARIO_PREPARATION_INPUTS_PATH: /mnt/inputs
      SCENARIO_PREPARATION_OUTPUTS_PATH: /mnt/outputs
    volumes:
      - type: bind
        source: ${SCENARIO_PREPARATION_INPUTS_PATH:-./inputs}
        # target must be kept in sync with config.yml
        target: /mnt/inputs
      - type: bind
        source: ${SCENARIO_PREPARATION_OUTPUTS_PATH:-./outputs}
        # target must be kept in sync with config.yml
        target: /mnt/outputs
