---
name: Run scenario preparation

# This workflow is based on, but diverges from the example here:
# https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners

on:
  workflow_call:
    inputs:
      image-tag:
        description: Tag for docker image
        required: true
        type: string
      resource-group:
        description: Resource Group to deploy container
        required: false
        default: RMI-SP-PACTA-PROD
        type: string

jobs:
  prep:
    name: Run workflow
    runs-on: ubuntu-latest
    strategy:
      # fail if any build fails
      fail-fast: false
      # build amd64 and arm64 in parallel
      matrix:
        config_active:
          - "2022Q4"
          - "2023Q4"
    # write to packages (ghcr.io)
    permissions:
      packages: read
      contents: read
      id-token: write

    steps:

      - name: Checkout repo
        uses: actions/checkout@v5

      # https://github.com/Azure/login?tab=readme-ov-file#login-with-openid-connect-oidc-recommended
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # https://github.com/marketplace/actions/azure-cli-action#workflow-to-execute-an-azure-cli-script-of-a-specific-cli-version
      - name: Start Container Instance
        uses: azure/CLI@v2
        env:
          FULL_IMAGE_NAME: ${{ inputs.image-tag }}
          R_CONFIG_ACTIVE: ${{ matrix.config_active }}
          RESOURCEGROUP: ${{ inputs.resource-group }}
        with:
          # azcliversion: 2.30.0
          inlineScript: |
            az --version
            IMAGE_TAG=$(echo $FULL_IMAGE_NAME | sed 's/^.*://')
            az deployment group create \
              --name "workflow.scenario.preparation-$R_CONFIG_ACTIVE" \
              --resource-group "$RESOURCEGROUP" \
              --template-file azure-deploy.json \
              --parameters azure-deploy.rmi-pacta.parameters.json \
              --parameters imageTag="$IMAGE_TAG" \
              --parameters rConfigActive="$R_CONFIG_ACTIVE"
